### ISSUE TITLE
Show an example of merging changes?

### ISSUE THREAD

**Issue by ajb** [diy/opensourcerer.diy.org#3]
Yo, this guide is awesome! 

When I first saw this illustration:

![](http://diy-visualpedia.s3.amazonaws.com/git-graphic-01.png)

I thought that it would show a merge -- i.e. Sam adds peacock feathers _before_ Jean pushes her tiger head commit. Is this something that should be included somewhere in the guide, or is it too complicated/not in the scope?

**Comment by jlord** [comment]
Thanks!

Yeah - we decided for this graphic to keep it simple and keep it in the scope of "make things better, together." It also doesn't address that the users forking this imaginary repo are also able to push without having been given access to the repo they've forked from...

The guide doesn't cover merges at all because we just have the users submit pull requests to our repo. This is the starting point - we would totally love for the kids on the site to do these challenges and then say "we want more!" and then we'll add round 2 and dive more into things like merging, branches and so on.
